server:
  address: 0.0.0.0
  port: 8080
  jpa:
    generate-ddl: true

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
  application:
    name: url-shortener